image: openbsd/latest
packages:
- xz
sources:
- https://github.com/euantorano/pledge.nim
environment:
  NIM_VERSION: 1.0.4
  CC: /usr/bin/clang
tasks:
- install_nim: |
    ftp -o nim.tar.xz https://nim-lang.org/download/nim-${NIM_VERSION}.tar.xz
    xz -d nim.tar.xz
    tar -xf nim.tar
    rm nim.tar
    cd nim-${NIM_VERSION}
    sh build.sh
    bin/nim c koch
- test: |
    cd pledge.nim
    env PATH="$HOME/nim-${NIM_VERSION}/bin:$PATH" nim c --cc:clang -r tests/main.nim
triggers:
- action: email
  condition: always
  to: Euan T <euan+pledge.nim@torano.co.uk>
